fix(deps): update dependency flowbite-react to ^0.12.0 (#445)
This PR contains the following updates:

| Package | Change | Age | Confidence |
|---|---|---|---|
| [flowbite-react](https://flowbite-react.com)
([source](https://redirect.github.com/themesberg/flowbite-react/tree/HEAD/packages/ui))
| [`^0.11.0` ->
`^0.12.0`](https://renovatebot.com/diffs/npm/flowbite-react/0.11.9/0.12.10)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/flowbite-react/0.12.10?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/flowbite-react/0.11.9/0.12.10?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>themesberg/flowbite-react (flowbite-react)</summary>

###
[`v0.12.10`](https://redirect.github.com/themesberg/flowbite-react/blob/HEAD/packages/ui/CHANGELOG.md#01210)

[Compare
Source](https://redirect.github.com/themesberg/flowbite-react/compare/flowbite-react@0.12.9...flowbite-react@0.12.10)

##### Patch Changes

-
[#&#8203;1631](https://redirect.github.com/themesberg/flowbite-react/pull/1631)
[`615fda0`](https://redirect.github.com/themesberg/flowbite-react/commit/615fda072f6f12385d3984b5bad69b1bac6da53b)
Thanks
[@&#8203;SutuSebastian](https://redirect.github.com/SutuSebastian)! - up
packages

###
[`v0.12.9`](https://redirect.github.com/themesberg/flowbite-react/blob/HEAD/packages/ui/CHANGELOG.md#0129)

[Compare
Source](https://redirect.github.com/themesberg/flowbite-react/compare/flowbite-react@0.12.8...flowbite-react@0.12.9)

##### Patch Changes

-
[#&#8203;1624](https://redirect.github.com/themesberg/flowbite-react/pull/1624)
[`e2b007f`](https://redirect.github.com/themesberg/flowbite-react/commit/e2b007fbd28d17c33d9e246f2ba9d2eca3fef037)
Thanks
[@&#8203;SutuSebastian](https://redirect.github.com/SutuSebastian)! -
fix(wrapDefaultExport): handle complex multiline exports

###
[`v0.12.8`](https://redirect.github.com/themesberg/flowbite-react/blob/HEAD/packages/ui/CHANGELOG.md#0128)

[Compare
Source](https://redirect.github.com/themesberg/flowbite-react/compare/flowbite-react@0.12.7...flowbite-react@0.12.8)

##### Patch Changes

-
[#&#8203;1621](https://redirect.github.com/themesberg/flowbite-react/pull/1621)
[`c02a977`](https://redirect.github.com/themesberg/flowbite-react/commit/c02a97717a881ad6c6be96baaf703ba45260105d)
Thanks
[@&#8203;SutuSebastian](https://redirect.github.com/SutuSebastian)! -
fix: Error: spawn npm ENOENT

###
[`v0.12.7`](https://redirect.github.com/themesberg/flowbite-react/blob/HEAD/packages/ui/CHANGELOG.md#0127)

[Compare
Source](https://redirect.github.com/themesberg/flowbite-react/compare/flowbite-react@0.12.6...flowbite-react@0.12.7)

##### Patch Changes

-
[#&#8203;1615](https://redirect.github.com/themesberg/flowbite-react/pull/1615)
[`50ae2ee`](https://redirect.github.com/themesberg/flowbite-react/commit/50ae2eeb147d3e6cb86c59c881762fa5874e3b20)
Thanks
[@&#8203;SutuSebastian](https://redirect.github.com/SutuSebastian)! -
fix(ui/cli/plugins): `setup-plugin-bun` also detect `Bun.build`

###
[`v0.12.6`](https://redirect.github.com/themesberg/flowbite-react/blob/HEAD/packages/ui/CHANGELOG.md#0126)

[Compare
Source](https://redirect.github.com/themesberg/flowbite-react/compare/flowbite-react@0.12.5...flowbite-react@0.12.6)

##### Patch Changes

-
[#&#8203;1612](https://redirect.github.com/themesberg/flowbite-react/pull/1612)
[`941a075`](https://redirect.github.com/themesberg/flowbite-react/commit/941a0758786a680b43c5c703ce9292b4a2781e14)
Thanks
[@&#8203;SutuSebastian](https://redirect.github.com/SutuSebastian)! -
Fix `nextjs` plugin to work on all environments

###
[`v0.12.5`](https://redirect.github.com/themesberg/flowbite-react/blob/HEAD/packages/ui/CHANGELOG.md#0125)

[Compare
Source](https://redirect.github.com/themesberg/flowbite-react/compare/flowbite-react@0.12.4...flowbite-react@0.12.5)

##### Patch Changes

-
[#&#8203;1608](https://redirect.github.com/themesberg/flowbite-react/pull/1608)
[`e1b5bb1`](https://redirect.github.com/themesberg/flowbite-react/commit/e1b5bb10b34b9d7fe77d19e1874c140558c054f9)
Thanks
[@&#8203;SutuSebastian](https://redirect.github.com/SutuSebastian)! -
fix: (node:50743) \[DEP0190] DeprecationWarning

###
[`v0.12.4`](https://redirect.github.com/themesberg/flowbite-react/blob/HEAD/packages/ui/CHANGELOG.md#0124)

[Compare
Source](https://redirect.github.com/themesberg/flowbite-react/compare/flowbite-react@0.12.3...flowbite-react@0.12.4)

##### Patch Changes

-
[#&#8203;1607](https://redirect.github.com/themesberg/flowbite-react/pull/1607)
[`a89a098`](https://redirect.github.com/themesberg/flowbite-react/commit/a89a09808bc1a5227e614aa160d932890fb1b126)
Thanks
[@&#8203;SutuSebastian](https://redirect.github.com/SutuSebastian)! -
fix: `Error: Cannot find module 'tailwindcss/plugin'`

-
[#&#8203;1605](https://redirect.github.com/themesberg/flowbite-react/pull/1605)
[`262cde0`](https://redirect.github.com/themesberg/flowbite-react/commit/262cde0defd27ac0496cbb5a4f0dc08261f6e094)
Thanks
[@&#8203;SutuSebastian](https://redirect.github.com/SutuSebastian)! -
Search for `<ThemeInit />` in the project and warn if it's not found
instead of warning all the time

##### Changes

- during commands `build` and `dev` check files content for custom
configuration and display a warning if `<ThemeInit />` is not found
- switch tests in `src/cli` and `src/helpers` from `vitest` ->
`bun:test`

###
[`v0.12.3`](https://redirect.github.com/themesberg/flowbite-react/blob/HEAD/packages/ui/CHANGELOG.md#0123)

[Compare
Source](https://redirect.github.com/themesberg/flowbite-react/compare/flowbite-react@0.12.2...flowbite-react@0.12.3)

##### Patch Changes

-
[#&#8203;1600](https://redirect.github.com/themesberg/flowbite-react/pull/1600)
[`12d3290`](https://redirect.github.com/themesberg/flowbite-react/commit/12d32902e5f01867e49927d0c508e6ad184686cd)
Thanks
[@&#8203;SutuSebastian](https://redirect.github.com/SutuSebastian)! -
fix(ui/cli/setup-init): nextjs warning

##### Changes

- [x] rename `config` -> `CONFIG` export in
`.flowbite-react/init.(jsx|tsx)`

###
[`v0.12.2`](https://redirect.github.com/themesberg/flowbite-react/blob/HEAD/packages/ui/CHANGELOG.md#0122)

[Compare
Source](https://redirect.github.com/themesberg/flowbite-react/compare/flowbite-react@0.12.1...flowbite-react@0.12.2)

##### Patch Changes

-
[#&#8203;1596](https://redirect.github.com/themesberg/flowbite-react/pull/1596)
[`ab26436`](https://redirect.github.com/themesberg/flowbite-react/commit/ab26436dab2de339c4cdc461317fb2548d554be0)
Thanks
[@&#8203;SutuSebastian](https://redirect.github.com/SutuSebastian)! -
refactor(setup-init): relax checks on React imports due to IDE
formatters removing it if not necessary

- filter out `import React from "react"` from the AST when parsing
current and new content

###
[`v0.12.1`](https://redirect.github.com/themesberg/flowbite-react/blob/HEAD/packages/ui/CHANGELOG.md#0121)

[Compare
Source](https://redirect.github.com/themesberg/flowbite-react/compare/flowbite-react@0.12.0...flowbite-react@0.12.1)

##### Patch Changes

-
[#&#8203;1594](https://redirect.github.com/themesberg/flowbite-react/pull/1594)
[`9017065`](https://redirect.github.com/themesberg/flowbite-react/commit/90170651ba4e113a792b6c493b7868094a1d382d)
Thanks
[@&#8203;SutuSebastian](https://redirect.github.com/SutuSebastian)! -
fix(compareNodes): support:

  ```
  - different quote styles
  - with and without semicolons
  - trailing commas in objects and arrays
  ```

  - add tests

###
[`v0.12.0`](https://redirect.github.com/themesberg/flowbite-react/blob/HEAD/packages/ui/CHANGELOG.md#0120)

[Compare
Source](https://redirect.github.com/themesberg/flowbite-react/compare/flowbite-react@0.11.9...flowbite-react@0.12.0)

##### Minor Changes

-
[#&#8203;1566](https://redirect.github.com/themesberg/flowbite-react/pull/1566)
[`7b79b18`](https://redirect.github.com/themesberg/flowbite-react/commit/7b79b18e63bc1bf25250186a55c439a534b8a254)
Thanks
[@&#8203;SutuSebastian](https://redirect.github.com/SutuSebastian)! - #
Breaking changes

  - removed `flowbite-react patch` CLI command

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/ziyadedher/dental-clutter).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS4xNTkuNCIsInVwZGF0ZWRJblZlciI6IjQxLjE1OS40IiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>